/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  About: ["introduction", "terminology", "history"],
  Wallets: [
    "wallet-guide",
    // "wallet-guide/apps",
    // {
    //   type: "category",
    //   label: "Web Wallets",
    //   items: ["wallet-guide/web-wallets", "wallet-guide/solflare"],
    // },
    // {
    //   type: "category",
    //   label: "Hardware Wallets",
    //   items: ["wallet-guide/ledger-live"],
    // },
    // {
    //   type: "category",
    //   label: "Command-line Wallets",
    //   items: [
    //     "wallet-guide/cli",
    //     "wallet-guide/paper-wallet",
    //     {
    //       type: "category",
    //       label: "Hardware Wallets",
    //       items: [
    //         "wallet-guide/hardware-wallets",
    //         "wallet-guide/hardware-wallets/ledger",
    //       ],
    //     },
    //     "wallet-guide/file-system-wallet",
    //   ],
    // },
    // "wallet-guide/support",
  ],
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'}
  ],
  // docs: {
  //   About: ["intro"]
  // }
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
