name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        cd .build/website
        yarn install
        yarn build
        yarn cname
        yarn gh-pages --dist build --user "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APP_GA_MEASUREMENT_ID: ${{ secrets.APP_GA_MEASUREMENT_ID }}
