name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: cd .build/website && yarn install && yarn build
